// Code generated by MockGen. DO NOT EDIT.
// Source: commit_history.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "ecnu.space/tmp-loser/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCommitHistoryReadWriter is a mock of CommitHistoryReadWriter interface
type MockCommitHistoryReadWriter struct {
	ctrl     *gomock.Controller
	recorder *MockCommitHistoryReadWriterMockRecorder
}

// MockCommitHistoryReadWriterMockRecorder is the mock recorder for MockCommitHistoryReadWriter
type MockCommitHistoryReadWriterMockRecorder struct {
	mock *MockCommitHistoryReadWriter
}

// NewMockCommitHistoryReadWriter creates a new mock instance
func NewMockCommitHistoryReadWriter(ctrl *gomock.Controller) *MockCommitHistoryReadWriter {
	mock := &MockCommitHistoryReadWriter{ctrl: ctrl}
	mock.recorder = &MockCommitHistoryReadWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommitHistoryReadWriter) EXPECT() *MockCommitHistoryReadWriterMockRecorder {
	return m.recorder
}

// CorrectAndInsert mocks base method
func (m *MockCommitHistoryReadWriter) CorrectAndInsert(ctx context.Context, commit *model.QuizQuestion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CorrectAndInsert", ctx, commit)
	ret0, _ := ret[0].(error)
	return ret0
}

// CorrectAndInsert indicates an expected call of CorrectAndInsert
func (mr *MockCommitHistoryReadWriterMockRecorder) CorrectAndInsert(ctx, commit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CorrectAndInsert", reflect.TypeOf((*MockCommitHistoryReadWriter)(nil).CorrectAndInsert), ctx, commit)
}

// GetCommitsByUserNameAndQuizID mocks base method
func (m *MockCommitHistoryReadWriter) GetCommitsByUserNameAndQuizID(ctx context.Context, userName string, quizID uint64) []model.CommitHistory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitsByUserNameAndQuizID", ctx, userName, quizID)
	ret0, _ := ret[0].([]model.CommitHistory)
	return ret0
}

// GetCommitsByUserNameAndQuizID indicates an expected call of GetCommitsByUserNameAndQuizID
func (mr *MockCommitHistoryReadWriterMockRecorder) GetCommitsByUserNameAndQuizID(ctx, userName, quizID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitsByUserNameAndQuizID", reflect.TypeOf((*MockCommitHistoryReadWriter)(nil).GetCommitsByUserNameAndQuizID), ctx, userName, quizID)
}

// GetQuizIDByUserNameAndPageNoAndNum mocks base method
func (m *MockCommitHistoryReadWriter) GetQuizIDByUserNameAndPageNoAndNum(ctx context.Context, userID string, pageNo, num uint64) []uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuizIDByUserNameAndPageNoAndNum", ctx, userID, pageNo, num)
	ret0, _ := ret[0].([]uint64)
	return ret0
}

// GetQuizIDByUserNameAndPageNoAndNum indicates an expected call of GetQuizIDByUserNameAndPageNoAndNum
func (mr *MockCommitHistoryReadWriterMockRecorder) GetQuizIDByUserNameAndPageNoAndNum(ctx, userID, pageNo, num interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuizIDByUserNameAndPageNoAndNum", reflect.TypeOf((*MockCommitHistoryReadWriter)(nil).GetQuizIDByUserNameAndPageNoAndNum), ctx, userID, pageNo, num)
}

// GetCommitsByQuestionID mocks base method
func (m *MockCommitHistoryReadWriter) GetCommitsByQuestionID(ctx context.Context, quizID uint64) []model.CommitHistory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitsByQuestionID", ctx, quizID)
	ret0, _ := ret[0].([]model.CommitHistory)
	return ret0
}

// GetCommitsByQuestionID indicates an expected call of GetCommitsByQuestionID
func (mr *MockCommitHistoryReadWriterMockRecorder) GetCommitsByQuestionID(ctx, quizID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitsByQuestionID", reflect.TypeOf((*MockCommitHistoryReadWriter)(nil).GetCommitsByQuestionID), ctx, quizID)
}

// GenQuiz mocks base method
func (m *MockCommitHistoryReadWriter) GenQuiz(userName string) []model.QuizQuestion {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenQuiz", userName)
	ret0, _ := ret[0].([]model.QuizQuestion)
	return ret0
}

// GenQuiz indicates an expected call of GenQuiz
func (mr *MockCommitHistoryReadWriterMockRecorder) GenQuiz(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenQuiz", reflect.TypeOf((*MockCommitHistoryReadWriter)(nil).GenQuiz), userName)
}
